FROM node:alpine AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

FROM cypress/browsers:node12.14.1-chrome85-ff81 AS cypress

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

