FROM node:12.16.2-alpine3.11
RUN apk update && apk add python2 make g++
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
ENV NODE_PATH /node_modules
ENV PATH $PATH:/node_modules/.bin
RUN echo "network-timeout 600000" > .yarnrc
RUN yarn install --verbose --har 
ADD . . 
EXPOSE 3000
CMD ["yarn", "start"]
#CMD ["sleep", "3000"]
